### PR TITLE
pr created by fuwalter

### PR DESCRIPTION
**Pull request by fuwalter**
Please consider this PR from the forked repo.

### CODE REVIEW

**Review by walterfu23 — COMMENTED** [review]
What is the reason for this PR?

**Comment by fuwalter** [comment]
To answer your question about the reason of the PR:
1. It can handle new requirements
2. It is a test.

**Review by walterfu23 — CHANGES_REQUESTED** [review]
would it be better this way:
(a) change this
(b) change that.

**Review by fuwalter — COMMENTED** [review]
the requested changes look good.

**Review by walterfu23 — APPROVED** [review]

**Pull request merged**
